### ISSUE TITLE
Docker Build Failure

### ISSUE THREAD

**Issue by ryan-clancy** [osirrc2019/nvsm-docker#2]
When building the image (either on Docker Hub or locally), the following error occurs: https://cloud.docker.com/u/osirrc2019/repository/registry-1.docker.io/osirrc2019/nvsm/builds/8cd5a4a4-a358-4174-8ce8-8dabeb123b8a

Can you take a look, @albpurpura?

**Comment by albpurpura** [comment]
Hey! thank you for trying that, the init file was missing, I added that to the repo. It should be working now.
